### PR TITLE
Update anomaly_detection.md

### PR DESCRIPTION
**Pull request by shuisman**
typo

### CODE REVIEW

**Comment by beckettsean** [comment]
@nathanielc @rossmcdonald

**Comment by nathanielc** [comment]
@sean LGTM! Thanks @shuisman

**Comment by beckettsean** [comment]
https://github.com/influxdata/docs.influxdata.com/commit/73934a2ef539588f162769455680b407b43c97a1 direct commit for 1.0 version

**Comment by shuisman** [comment]
Awesome!

**Pull request merged**
