### PR TITLE
making the disclaimer less scary

### PR DESCRIPTION
**Pull request by beckettsean**
updating 0.10 to be more descriptive and less offputting.

### CODE REVIEW

**Comment by beckettsean** [comment]
@rkuchan @mjdesa @rossmcdonald @jackzampolin @jwilder @jginfluxdata @fred-influx 

Are you okay with this update to the clustering guide?

**Comment by jwilder** [comment]
No.  I would say it is still experimental in 0.10.

**Comment by gunnaraasen** [comment]
@beckettsean the proposed wording makes clustering sound better than it is. I think we can remove the "experimental" label but still make the warning more descriptive of the current state of clustering.

E.g. "Clustering works but is still in active development and not yet feature complete. There are rough edges and edge-case failure scenarios have not been fully tested. If you encounter any issues, please [report them](https://github.com/influxdata/influxdb/issues/new)."

**Comment by beckettsean** [comment]
Leaving it as-is for now, will update when a more nuanced picture is available.

**Pull request closed without merging**
