### PR TITLE
correct grammar

### PR DESCRIPTION
**Pull request by jademcgough**
I believe this content is duplicated in every kapacitor node doc, so we'd need to make sure that this propagates to those as well.

### CODE REVIEW

**Comment by beckettsean** [comment]
@nathanielc more for the Kap source

**Comment by beckettsean** [comment]
@nathanielc perhaps you can show @rkuchan and I where to change this so we can update the Kap docs and leave you out of the critical path?

**Comment by nathanielc** [comment]
@rkuchan @beckettsean The docs just come from comments in the code. All the relevant code lives in this directory https://github.com/influxdata/kapacitor/tree/master/pipeline 

For example https://github.com/influxdata/kapacitor/blob/master/pipeline/node.go#L357

I would appreciate a PR against Kapacitor with these changes :)

**Comment by jademcgough** [comment]
moving this to https://github.com/influxdata/kapacitor/pull/852

**Pull request closed without merging**
