### PR TITLE
Better Looking Landing Page

### LINKED ISSUE #639: Enterprise section on the docs landing page needs love
###### URL for relevant page?
https://docs.influxdata.com/

The Enterprise section on the docs landing page is lonely:
image

### PR DESCRIPTION
**Pull request by alexpaxton**
Don’t really have “brand colors” for Enterprise yet, so rolling with
this for now. Fixes #639 

screen shot 2016-09-02 at 12 00 47 pm
screen shot 2016-09-02 at 12 01 59 pm

### CODE REVIEW

**Comment by beckettsean** [comment]
Looks good to me!

**Comment by toddboom** [comment]
:+1:

**Comment by rkuchan** [comment]
The link to the Enterprise Getting Started page should be `/enterprise/v1.0/introduction/getting-started/` instead of `/enterprise/v1.0/introduction/getting_started/`. I failed at trying to fix it myself.

**Comment by rkuchan** [comment]
The Downloads page doesn't go anywhere productive at the moment. It will once https://github.com/influxdata/docs.influxdata.com/issues/634 is fixed.

**Pull request merged**
