### PR TITLE
update reporting description

### LINKED ISSUE #507: update monitoring language
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.13/administration/config/#reporting-disabled-false

###### What products and version are you using?
Relevant for all versions of InfluxDB, all docs should be updated.

New wording:

InfluxData, the company, relies on reported data from running nodes primarily to track the adoption rates of different InfluxDB versions. This data helps InfluxData support the continuing development of InfluxDB. 

The `reporting-disabled` option toggles the reporting of data every 24 hours to `m.influxdb.com`. Each report includes a unique, randomly-generated identifier (an 8-byte Raft ID), OS, architecture, InfluxDB version, and the number of [databases](definition), [measurements](definition), and unique [series](definition). Setting this option to `true` will disable reporting.

### PR DESCRIPTION
**Pull request by beckettsean**
fixes #507

### CODE REVIEW

**Comment by beckettsean** [comment]
@rkuchan @gunnaraasen

**Comment by jackzampolin** [comment]
We started tracking `uptime` in 0.13 as well.

**Comment by pauldix** [comment]
👍

**Comment by rkuchan** [comment]
@beckettsean I missed the initial conversation but should the changes also be part of the 1.0 docs?

**Comment by beckettsean** [comment]
Thanks, @rkuchan. I did the changes but I guess I didn't check them in. Done now.

**Comment by beckettsean** [comment]
something looks wrong, hold on a sec

**Comment by beckettsean** [comment]
Okay, fixed. @rkuchan good to merge?

**Comment by rkuchan** [comment]
@beckettsean yup! Not sure if you get notified if I smiley face your comment...

**Comment by beckettsean** [comment]
@rkuchan I do not get a notice for smileys, so thanks for the note!

**Pull request merged**
