### PR TITLE
Add documentation for DROP SHARD, DROP SERVER, SHOW SERVERS

### PR DESCRIPTION
**Pull request by rkuchan**
`DROP SHARD`:
* Relevant version: 0.11
* Adds description to the query language reference and database management docs
* Fixes https://github.com/influxdata/docs.influxdata.com/issues/339

`DROP SERVER`:
* Relevant versions: 0.10,0.11
* Adds description to the query language reference doc and adds a link to the cluster setup doc
* Adds `META` and `DATA` to keywords in query language reference doc
* Fixes https://github.com/influxdata/docs.influxdata.com/issues/186

`SHOW SERVERS`:
* Relevant versions: 0.10,0.11
* Adds description to the query language reference doc

### CODE REVIEW

**Comment by beckettsean** [comment]
@e-dard can you please review?

@jwilder who else should review the Docs PR for `DROP SHARD`, `DROP SERVER`, and `SHOW SERVERS`?

**Comment by jwilder** [comment]
LGTM.  `Drop server` is going to be removed.  `show servers` likely will be as well too.

**Comment by e-dard** [comment]
:+1: Ship it.

**Comment by rkuchan** [comment]
Thank you!
@e-dard, best ship it message yet.

**Pull request merged**
