### PR TITLE
Add influxdb-nodejs

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by beckettsean** [comment]
@dandv that library isn't fully 1.0 compliant and hasn't been updated for two months. Do you know if the maintainer is active?

**Comment by dandv** [comment]
>  hasn't been updated for two months

How strong of a criterion is the update frequency? The [influent library hasn't been updated since last year](https://github.com/gobwas/influent/issues/19).

**Comment by beckettsean** [comment]
See https://github.com/influxdata/docs.influxdata.com/issues/771

**Comment by vicanso** [comment]
@beckettsean @dandv 
Sure,I maintain this project continuously. This project is basically for my daily developments, therefore, modification will not be frequent unless I need it.

**Pull request closed without merging**
