### PR TITLE
Docs Re-Design

### PR DESCRIPTION
**Pull request by alexpaxton**
# Overview
Now that there’s a build tool set up, I took the opportunity to not only refactor all the CSS into LESS, but went ahead and tackled some bug fixes as well as some design updates. The biggest changes are under the hood: separate `.less` files for each component, site wide variables to standardize media queries and responsive behavior, everything is minified and concatenated for maximum awesome.

### Changes
- Modularized CSS, much easier to navigate
- Created theme files
- Implemented a crude theme switcher
- Toggle themes from button in nav
- Sidebar more compact
- Text overall is more compact
- Moved product switcher to navbar
- Fixed scrolling bug (now the page will scroll to the right place when an anchor is in the URL)

### Still needs work
- Support ad needs to be added back in
- During refactor, separate color schemes for each product have been lost, need to re-implement
- Theme switcher generates a cookie, but encounters a bug when trying to read the cookie (themes do not persist beyond refresh)

### CODE REVIEW

**Comment by alexpaxton** [comment]
screen shot 2016-03-24 at 5 11 11 pm
screen shot 2016-03-24 at 5 11 18 pm
screen shot 2016-03-24 at 5 11 47 pm
screen shot 2016-03-24 at 5 12 18 pm

**Comment by beckettsean** [comment]
@kostasb can we deploy this branch to staging? No sense in reviewing CSS anywhere but live.

**Comment by pauldix** [comment]
OMG yassss. I vote for the light theme being the default.

Seems like it can't be deployed until the needs work stuff is done?

**Comment by kostasb** [comment]
Staging for 'ap-less-cleanup' branch:

http://docs.staging.influxdata.com:31001/

**Comment by beckettsean** [comment]
Multi-line left nav items are difficult to distinguish. Maybe we need indentation or wider newline kerning?

screen shot 2016-03-28 at 10 13 43

**Comment by alexpaxton** [comment]
Just added in text indenting for multi-line sidebar items
screen shot 2016-03-28 at 10 32 22 am

**Comment by beckettsean** [comment]
In the light theme, the green Note text is difficult to read: 

screen shot 2016-03-28 at 17 41 56

**Comment by alexpaxton** [comment]
@beckettsean tweaked those guys, here's a preview
screen shot 2016-03-28 at 6 31 48 pm
screen shot 2016-03-28 at 6 31 26 pm

**Comment by beckettsean** [comment]
@alexpaxton @rkuchan @pauldix 

There are some really great improvements in this PR and we would love to get them merged in time for the 0.13 docs release. Is there any chance we can close out the remaining issues by mid-next week?

How can support team help?

**Comment by alexpaxton** [comment]
@beckettsean I need someone to take a look at the cookie for theme preference. I need to add the Support Ad back in, which shouldn't take long. Mid-next week sounds very doable

**Comment by beckettsean** [comment]
@mark-rushakoff @willpiers @wfro @121watts @mjdesa can one of you folks blessed with front-end know-how take a look at @alexpaxton's cookie issue?

The job pays actual cookies of your choice.

**Comment by toddboom** [comment]
taking a look at this today

**Comment by toddboom** [comment]
(i want to win the cookies.)

**Comment by toddboom** [comment]
@alexpaxton Only one small issue i noticed - the background color below the end of a page stays dark even in the light theme. It's only noticeable on "short" pages, like the intro pages:
http://localhost:1313/chronograf/v0.10/

I think it may literally just be the `background-color` on body that needs to change.

**Comment by alexpaxton** [comment]
## Adding in support ads

At the top of the sidebar, big prominent green button hopefully gets lots of tasty clicks
screen shot 2016-05-10 at 1 01 51 pm

Also adding a more subtle link in the `contribute` partial, because it doesn't hurt to have more links to this stuff
screen shot 2016-05-10 at 1 02 01 pm

**Comment by gunnaraasen** [comment]
One last thing, the warning on old versions overlaps and obscures the sidebar.

screen shot 2016-05-10 at 1 15 15 pm

**Comment by rkuchan** [comment]
@alexpaxton, I tried fixing the merge conflict. The warning shows up but I want to make sure this is what you want it to look like: 

image

**Comment by beckettsean** [comment]
🎉 🎉 🎉 🎆 💯 🎡 👊

**Pull request merged**
