### PR TITLE
Kapacitor Documentation Restructure

### PR DESCRIPTION
**Pull request by rossmcdonald**
Updates:

- Broke TICKscript property methods into their own heading in the sidebar. Now there are two headings for TICKscripts: 
  - TICKscript Overview - discusses overview of TICKscript architecture and specification
  - TICKscript Property Methods - discusses each property method node in detail
- Added an index page to the Property Method sidebar.
- Moved Batch and Stream node to be at the top of the Property Method sidebar for easy access.
- Moved Examples sidebar above TICKscript reference.

### CODE REVIEW

**Comment by rossmcdonald** [comment]
/cc @rkuchan @nathanielc @gunnaraasen 

Some architectural updates to the Kapacitor documentation. The goal here is to improve the overall structure and be a little easier to digest for newcomers.

I am very open to thoughts and criticism, so let me know what you guys think.

**Comment by nathanielc** [comment]
@rossmcdonald  I like this changes, just a couple of thoughts:

*  `TICKScript Property Methods` -> `TICKScript Nodes` and the folder from `methods` to `nodes`
* The node documentation is auto-generated, but can easily be moved to a new folder like you have it.

I would like to fix two more things in addition to these changes:

* Make each heading a link to itself via anchors so it is easier to share specific sections of the docs.
* Fix the issue that anchors only work sometimes. Details below.

Details on the anchors not working right:

1.  Click on this link http://docs.influxdata.com/kapacitor/v0.10/tick/window_node/#alert
 It should take you to the Window Node docs at the section about the Alert chaining method.
2. Click on the link in `Returns: AlertNode` 
3. Click back.

Now you are at the top of the WindowNode docs and not at the Alert method section. This makes it really easy to get lost in the docs. 

Also I am working on the v0.11 docs PR. I added an index near the top of each node so that it is easier to see what methods are property method and chain methods for a given node. I haven't submitted the PR yet since its is not ready but I would like feedback on the layout of the index. https://github.com/influxdata/docs.influxdata.com/tree/nc-kapacitor-v0.11

**Comment by rossmcdonald** [comment]
@nathanielc I think I may have fixed the anchor issue. Can you try rebuilding this branch to see if it's working for you now?

Also I renamed `methods` to `nodes`. I'll be taking a look at the 0.11 PR shortly.

**Comment by rossmcdonald** [comment]
Nevermind, I think I just broke scrolling. From what I can tell there's something that keeps bringing the scrollbar to the top on every reload, which is why the anchors aren't working. Not sure what that could be, though.

**Comment by gunnaraasen** [comment]
https://github.com/influxdata/docs.influxdata.com/pull/311 will fix the missing anchor links on the headers. I'm still looking into why the back button does not respect the anchor.

**Comment by gunnaraasen** [comment]
The pages that have moved should have an `alias` added to their front matter. E.g

```
aliases:
  - /kapacitor/v0.10/nodes/reduce_node/
```

And all the pages in `/content/kapacitor/v0.10/nodes/*.old` should be removed.

**Comment by gunnaraasen** [comment]
+1 once the aliases are added and the old files are removed.

**Comment by nathanielc** [comment]
+1 on this as well as soon the issues are fixed. Thanks @rossmcdonald

**Comment by rossmcdonald** [comment]
So I think this is ready to go:
- renamed `methods` -> `nodes`
- aliases have been added for the `tick` -> `nodes` switch
- the `.old` files have been rebased out

The anchors are still not working properly, but we may need a designer to take a look at what is causing that.

@nathanielc once this is merged, I'll take a look at the 0.11 docs.

**Comment by nathanielc** [comment]
@rossmcdonald just pulled this locally and it looks great, :shipit:

**Comment by gunnaraasen** [comment]
@rossmcdonald do the anchor links work if you rebase onto master?

**Comment by rossmcdonald** [comment]
@gunnaraasen This branch is rebased onto master, but it's still not working for me. Using @nathanielc's repro case above, using the back button still only takes you back to the top of the page (even though the URL is for the anchor).

**Comment by gunnaraasen** [comment]
Oh right, anchor links should work correctly but the back button behavior is still an issue. I've opened https://github.com/influxdata/docs.influxdata.com/issues/322 to track it.

Everything else looks good now. +1

**Pull request merged**
