### PR TITLE
adding 0.11 dl links

### LINKED ISSUE #405: 0.12 upgrading should give 0.11 binary URL
###### URL for relevant page?
http://docs.influxdata.com/influxdb/v0.12/administration/upgrading/
###### What products and version are you using?
upgrading from InfluxDB 0.9 and need to export/import the metastore via `backup`, which doesn't exist in 0.9. I can't use 0.12 since the metastore has changed. I can't find out how to download 0.11 in order to have the backup.

Should add at least 
https://dl.influxdata.com/influxdb/releases/influxdb_0.11.1-1_amd64.deb
and 
https://dl.influxdata.com/influxdb/releases/influxdb-0.11.1-1.x86_64.rpm
plus whatever the raw binary is for those not on apt or yum

### PR DESCRIPTION
**Pull request by beckettsean**
fixes #405

### CODE REVIEW

**Comment by beckettsean** [comment]
@rkuchan @gunnaraasen @rossmcdonald 

The one remaining question is what advice to give Homebrew users. I don't know how they would fetch 0.11.1 from Homebrew if they already upgraded to 0.12. Thoughts?

**Comment by rossmcdonald** [comment]
I'm not sure if you can easily downgrade using Homebrew alone. As a worst case scenario, they can always download the binaries manually:

```
# Stop 0.12 server

# Download and start 0.11 server
wget https://dl.influxdata.com/influxdb/releases/influxdb-0.11.1-1_darwin_amd64.tar.gz
tar -xvf influxdb-0.11.1-1_darwin_amd64.tar.gz
./influxdb-0.11.1-1/usr/bin/influxd

# In a new window, run the backup
./influxdb-0.11.1-1/usr/bin/influxd backup /tmp/backup
```

**Comment by beckettsean** [comment]
updated with better formatting and @rossmcdonald's suggestions.

**Comment by gunnaraasen** [comment]
LGTM I've been wanting to set up our own Homebrew tap with older versions which would make rolling back to an earlier version much easier.

**Pull request merged**
