### PR TITLE
Fix numbered list on live_leaderboard example

### PR DESCRIPTION
**Pull request by russorat**

### CODE REVIEW

**Comment by timhallinflux** [comment]
perhaps merge this into the other Kapacitor doc updates and retire this branch?

**Comment by karel-rehor** [comment]
I've added these changes directly into the Kapacitor 1.4 release branch... 

https://github.com/influxdata/docs.influxdata.com/commit/b1c9a19dad0284b76e9739d59227955b8d8060a4

**Comment by russorat** [comment]
@karel-rehor so i can close this one?

**Comment by karel-rehor** [comment]
I think this can be closed

**Pull request closed without merging**
