### PR TITLE
Fix wrong gitlab oauth config for Chronograf

### PR DESCRIPTION
**Pull request by wzxjohn**
1. Correct the wrong param name (double GENERIC_CLIENT_ID on line 384 & 398 )
2. Add public url option for auto generate redirect uri
3. Correct the GENERIC_SCOPES option
4. Correct the callback url on line 360
5. Add remind for select correct scope on gitlab config page

### CODE REVIEW

**Comment by 4ndv** [comment]
This definitely should be merged, allowing `api` scope seems a little bit dangerous and the current documentation is just incorrect in so many ways.

**Comment by sanderson** [comment]
@wzxjohn If you'll resolve the merge conflicts, we'll go ahead and merge this. Thanks for the contribution!

**Comment by wzxjohn** [comment]
@sanderson Conflicts resolved.

**Comment by sanderson** [comment]
Thanks @wzxjohn!

**Pull request merged**
