### PR TITLE
Create before_you_begin

### PR DESCRIPTION
**Pull request by beckettsean**
@rkuchan @jwilder @kostasb @jackzampolin @rossmcdonald 

First pass at a "Cluster stuff you can't ignore!" doc. Lemme know what you think. Would like to merge before Monday.

### CODE REVIEW

**Comment by jackzampolin** [comment]
I feel like you should rename `Use three and only three Meta nodes` to `USE THREE AND ONLY THREE META NODES!!!` but that might be too aggressive. Looks great @beckettsean

**Comment by rkuchan** [comment]
@beckettsean, I was thinking that this could live in `Installation Guidelines` - what do you think? I could change the title to `Installation Guidelines (Please Read)`.

I like that structure because it's consistent with the format of the docs for the other projects. I am, however, willing to break from that consistency if you feel strongly about it.

**Comment by beckettsean** [comment]
@rkuchan that works well for me, and I defer to your judgment.

**Comment by beckettsean** [comment]
@rkuchan I'll let you edit this branch directly and merge when you are ready, okay?

**Pull request merged**
