### PR TITLE
Reformat table

### PR DESCRIPTION
**Pull request by ducnt114**

### CODE REVIEW

**Comment by sanderson** [comment]
Thanks for the contribution @ducnt114. Was there an issue with the formatting of the previous table that was causing to not appear correctly for you?

**Comment by ducnt114** [comment]
@sanderson Table format was broken as you can see in https://docs.influxdata.com/influxdb/v1.7/concepts/storage_engine/

**Comment by sanderson** [comment]
@ducnt114 It appears correctly for me. Can you take a screenshot of how it renders for you?

**Comment by ducnt114** [comment]
This is how the table rendered on my macbook pro 13"
Screen Shot 2019-09-11 at 4 00 44 PM

**Pull request merged**
