### PR TITLE
Add upgrade steps for linking pre-existing users to web console users

### PR DESCRIPTION
**Pull request by rkuchan**
Adds an additional step to the upgrade process.

### CODE REVIEW

**Comment by rkuchan** [comment]
@beckettsean, here's what I put together. The new user structure can be a little confusing. Let me know if anything doesn't make sense.

**Comment by beckettsean** [comment]
@rkuchan looks good to me, thanks!

**Comment by beckettsean** [comment]
@rkuchan I assume this will merge today and go live tonight?

**Comment by rkuchan** [comment]
Thanks, @beckettsean! Found WIFI again :).

**Pull request merged**
