### PR TITLE
0.10.0 Clustering Documentation

### PR DESCRIPTION
**Pull request by rossmcdonald**

### CODE REVIEW

**Comment by beckettsean** [comment]
@rossmcdonald do you want feedback yet?

**Comment by rossmcdonald** [comment]
@beckettsean Yes, always. I tried to simplify the process a bit, but I'd like a fresh set of eyes on it to help identify any spots that are particularly confusing.

**Comment by toddboom** [comment]
:+1:

**Comment by gunnaraasen** [comment]
+1

One suggestion, may want to link to some further documentation on managing meta and data nodes to the end of the guide.

**Comment by rossmcdonald** [comment]
Merging. Will definitely need to revisit in the near future, though.

**Pull request merged**
