### PR TITLE
add release notes for Kapacitor 1.5.5

### PR DESCRIPTION
**Pull request by kelseiv**
Add Kapacitor 1.5.5 release notes

### CODE REVIEW

**Comment by docmerlin** [comment]
@kelseiv that is a good call on the wording.

**Comment by kelseiv** [comment]
Thanks, @timhallinflux - not in install or config docs, but did see

 MD5 in  [_Calculating rates across joined series + backfill_](https://docs.influxdata.com/kapacitor/v1.5/guides/join_backfill/#the-data-generator).

Does it make sense to drop md5 link here and/or update [page.zip](https://docs.influxdata.com/downloads/pages.zip)?

**Comment by docmerlin** [comment]
@kelseiv I'm not tim, but since you asked me to comment.  If we are standardizing on sha256 everywhere,  then it makes sense to drop the md5 link.

**Comment by kelseiv** [comment]
thank you, @docmerlin! Do we need to update /repackage any of the python script in page.zip?

**Comment by docmerlin** [comment]
@kelseiv no

**Pull request merged**
