### PR TITLE
Docs for socket based UDFs in Kapacitor

### PR DESCRIPTION
**Pull request by nathanielc**

### CODE REVIEW

**Comment by beckettsean** [comment]
@rossmcdonald or @gunnaraasen can you review this?

**Comment by rossmcdonald** [comment]
On it.

**Comment by rossmcdonald** [comment]
@nathanielc Updated with small fixes around grammar/punctuation and wording. Let me know if you think the changes look okay.

**Comment by nathanielc** [comment]
@rossmcdonald +1

**Pull request merged**
