### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by rkuchan**
Fixes: 

* https://github.com/influxdata/docs.influxdata.com/issues/609 (Removes 0.9 from the AWS bucket that has `NOAA_data.txt`)
* https://github.com/influxdata/docs.influxdata.com/issues/637 (Removes differences.md from Chronograf 1.0 and add update the upgrading page)
* Updates the InfluxEnterprise backup and restore doc - this is almost all Mark's work and Joe's work
* #641 (Add documentation about bind parameters to the API reference - also moves around examples for legibility)
* https://github.com/influxdata/docs.influxdata.com/issues/351 (Adds descriptions for how to use CQs to get the same functionality as nested functions and HAVING clauses)
* https://github.com/influxdata/docs.influxdata.com/issues/654 (Fixes name of Enterprise getting started file so that landing page link works)
* https://github.com/influxdata/docs.influxdata.com/issues/652 (Adds compatibility guarantee to InfluxDB docs)

### CODE REVIEW

**Comment by beckettsean** [comment]
removed the file redirect, since it leads to a zero byte file and a .1 file:


```
sean@catalyst-sean:~$ wget https://s3.amazonaws.com/noaa.water-database/NOAA_data.txt > NOAA_data.txt
--2016-08-31 17:23:57--  https://s3.amazonaws.com/noaa.water-database/NOAA_data.txt
Resolving s3.amazonaws.com... 54.231.49.244
Connecting to s3.amazonaws.com|54.231.49.244|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5075892 (4.8M) [text/plain]
Saving to: 'NOAA_data.txt.1'

NOAA_data.txt.1                         100%[=================================================================================>]   4.84M  3.11MB/s   in 1.6s   

2016-08-31 17:23:59 (3.11 MB/s) - 'NOAA_data.txt.1' saved [5075892/5075892]

sean@catalyst-sean:~$ ll NOAA_data.txt*
-rw-r--r--  1 sean  staff        0 Aug 31 17:23 NOAA_data.txt
-rw-r--r--  1 sean  staff  5075892 Aug 31 16:40 NOAA_data.txt.1
```

**Comment by rkuchan** [comment]
After talking to @mark-rushakoff about backup and restore I discovered that that functionality has been updated for the 1.0 release.    https://github.com/influxdata/docs.influxdata.com/pull/636/commits/715a0b172a12af76418f5ee1f68610f7540b6ae8 is the almost new backup and restore doc. It's basically Mark's doc with some of the information from Joe's Confluence page on backup and restore.

Almost all of the issues that @goller mentioned in https://github.com/influxdata/docs.influxdata.com/issues/629 are now void.

**Comment by rkuchan** [comment]
@beckettsean, this should be good to go. I'll be doing the InfluxEnterprise updates in a different branch.

**Comment by beckettsean** [comment]
@rkuchan I'm not clear on what needs review here. The backup/restore stuff?

**Comment by rkuchan** [comment]
@beckettsean, `Update backup and restore doc`,  `Add docs about bind parameters, #641`, and `Add CQ workarounds for nested functions and HAVING clauses, #351` are the main ones.

**Pull request merged**
