### PR TITLE
enterprise navbar with influxdb entries

### PR DESCRIPTION
**Pull request by beckettsean**
fixes https://github.com/influxdata/docs.influxdata.com/issues/761

### CODE REVIEW

**Comment by beckettsean** [comment]
@rkuchan @gunnaraasen I think this should do the trick. I might have missed some syntax, please let me know if I need to fix stuff.

**Comment by beckettsean** [comment]
hmm, I had some sort of branch error, I need to clean up one thing.

**Comment by beckettsean** [comment]
master might be a little weird right now, my apologies. Once this merges everything should be cool.

fixes https://github.com/influxdata/docs.influxdata.com/issues/761

**Comment by rkuchan** [comment]
@beckettsean, awesome. I made some changes - once you're OK with them I'll squash these commits into one and merge!

**Comment by beckettsean** [comment]
@rkuchan changes work for me!

**Comment by rkuchan** [comment]
Closing due to inactivity. This is a possible solution to the Enterprise/OSS docs divide.

**Pull request closed without merging**
