### PR TITLE
proposed changes to eval docs

### PR DESCRIPTION
**Pull request by beckettsean**

### CODE REVIEW

**Comment by beckettsean** [comment]
@rossmcdonald @nathanielc

**Comment by nathanielc** [comment]
@beckettsean These changes look good. But since they are part of the auto generated docs they need to be changed in the Kapacitor source in order to be permanent. I'll port these changes over to a Kapacitor PR and then submit a new docs PR after generating.

Thanks!

**Comment by beckettsean** [comment]
Thanks, @nathanielc. Do we need to do the same for https://github.com/influxdata/docs.influxdata.com/pull/618? That doesn't seem auto-generated

**Comment by nathanielc** [comment]
See https://github.com/influxdata/kapacitor/pull/846

**Comment by nathanielc** [comment]
@beckettsean Nope, only docs under a `nodes` directory are auto generated.  Thanks for checking. I'll take a look at #618.

**Pull request closed without merging**
