### PR TITLE
Updates to Kapacitor Getting Started for Telegraf v0.10

### PR DESCRIPTION
**Pull request by nathanielc**
Since Telegraf v0.10 changed names of measurements and fields the Kapacitor getting started guide was out dated. These fixes update the getting started guide accordingly.

### CODE REVIEW

**Comment by rossmcdonald** [comment]
@nathanielc Aww, I should have coordinated this with you: #193 We can use this version, though, as you have some more extensive edits than mine. Sorry for the duplicated effort, though. :(

@rkuchan Do you mind reviewing this one as well?

**Comment by nathanielc** [comment]
No problem, I just kept getting issues filed with confusion from the guide so I just took a few minutes and got it done. I'll check open PRs next time too.

**Comment by rkuchan** [comment]
It might be nice to keep the paragraph below (maybe in a note), but otherwise this looks good to me!

If Kapacitor is not receiving data yet, check each layer: Telegraf -> InfluxDB -> Kapacitor. Telegraf will log errors if it cannot communicate to InfluxDB. InfluxDB will log an error about connection refused if it cannot send data to Kapacitor. Run the query SHOW SUBSCRIPTIONS to find the endpoint that InfluxDB is using to send data to Kapacitor.

**Comment by nathanielc** [comment]
@rkuchan That paragraph was moved down to where it's easier to tell if Kapacitor is receiving data.

**Comment by nathanielc** [comment]
@rossmcdonald @rkuchan Am I good to merge?

**Comment by rossmcdonald** [comment]
Merge away!

**Pull request merged**
