### PR TITLE
Switching to semantic linefeeds

### PR DESCRIPTION
**Pull request by beckettsean**
Quick and dirty regex to do most of it. Numbered lists were not well preserved, I don't know of any other issues yet.

I used `s/([\.\!\?])\s+(.*?)/$1\n$2` to create semantic line feeds in the docs. Before that substitution, multiple consecutive `\n` were protected using `s/{\n,}/XXXXX/` and then later restored with `s/XXXXX/\n\n/`.

### CODE REVIEW

**Comment by beckettsean** [comment]
@rkuchan I think numbered lists will need some fixing but I haven't seen anything else amiss so far.

**Comment by beckettsean** [comment]
Fixes #131

**Comment by rkuchan** [comment]
Thanks, @beckettsean! I went through and fixed up the numbered lists. 👍

**Comment by beckettsean** [comment]
Here goes nothing...

@gunnaraasen @rkuchan @mjdesa @rossmcdonald @kostasb @jackzampolin @toddboom please keep an eye on the docs after the next push. This was a huge mostly automated change, and I'm sure at least one or two inadvertent edits slipped through.

**Pull request merged**
