### PR TITLE
Several typos

### PR DESCRIPTION
**Pull request by e-dard**
Some small edits from reviewing the docs.

### CODE REVIEW

**Comment by rkuchan** [comment]
Thank you, @e-dard!  I made one small change - if that change is OK with you I'll get this merged.

**Comment by jademcgough** [comment]
I believe the changes to the index content in `influx_q_l_node.md` will need to be propagated to all other kapacitor node docs.

**Comment by beckettsean** [comment]
@jademcgough @rkuchan @e-dard 

Actually, those docs are auto-generated from the Kapacitor source, so @nathanielc needs to update the Kapacitor repo with the changes. Then they will propagate to all other nodes.

**Comment by nathanielc** [comment]
Relevant Kapacitor PR for he InfluxQL changes. Thanks @e-dard

**Pull request closed without merging**
