### PR TITLE
Clarity and consistency in the glossary of a "point"

### PR DESCRIPTION
**Pull request by zgohr**

### CODE REVIEW

**Comment by beckettsean** [comment]
The tag set implies the series and vice versa, so these additions are redundant.

**Comment by beckettsean** [comment]
I understand it might increase short-term comprehension to include the tag set, but that obscures the fact that the tag set and the series are one and the same (within a given measurement).

**Comment by zgohr** [comment]
Ah. Well that's confusing. Thanks for the clarification. Might want to take a look [writing duplicate points](https://docs.influxdata.com/influxdb/v0.10/troubleshooting/frequently_encountered_issues/#writing-duplicate-points) in the FAQ, as it describes it using measurement/tag set and could potentially then be written as series instead. Or maybe a point isn't a duplicate if its same series, tag set, and different retention policy?

**Comment by beckettsean** [comment]
Different retention policy does mean different point. In essence, the tag sets are scoped to a retention policy.

**Pull request closed without merging**
